services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse_server
    ports:
      - "8123:8123"    # HTTP interface
      - "9000:9000"    # Native TCP interface
    environment:
      - CLICKHOUSE_USER=your_user
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
      - CLICKHOUSE_PASSWORD=your_password
      - CLICKHOUSE_CONFIG_LISTEN_HOST=0.0.0.0
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./logs:/var/log/clickhouse-server
      - ./media:/usr/media   # CSVs accessible in /media inside the container
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  pytorch:
    build: .
    #image: pytorch/pytorch:2.7.1-cuda12.8-cudnn9-runtime
    container_name: chatbot
    #command: sleep infinity   # Keeps container running for interactive work
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ./media:/usr/workspace/media
      - ./notebooks:/usr/workspace/notebooks
    tty: true

volumes:
  clickhouse_data: